In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
A.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [3]:
A =np.array([[1,2],[3,4]])
B =np.array([[4,3],[2,1]])
C =np.array([[0,1],[1,0]])

In [4]:
A+B
#print(A+B)

array([[5, 5],
       [5, 5]])

In [5]:
print(3*C)
print(A+2*C)

[[0 3]
 [3 0]]
[[1 4]
 [5 4]]


In [6]:
O = np.zeros([2,2])
print(O)

[[0. 0.]
 [0. 0.]]


In [7]:
A = np.array([[1,-1],[0,1]])
B = np.array([[2,5],[1,3]])
print(A*B)
print("="*20)
print(np.dot(A,B))
print("="*30)
print(np.dot(B,A))

[[ 2 -5]
 [ 0  3]]
[[1 2]
 [1 3]]
[[2 3]
 [1 2]]


In [8]:
I4 = np.identity(4)
#I4 = np.eye(4)
print(I4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
I2 = np.identity(2)
print(np.all(np.dot(A,I2) == A) )
print(np.dot(I2, A) == A)

True
[[ True  True]
 [ True  True]]


In [10]:
np.linalg.det(A)

1.0

In [11]:
np.linalg.inv(A)

array([[1., 1.],
       [0., 1.]])

In [12]:
np.linalg.det(O)

0.0

In [13]:
np.linalg.inv(O)

LinAlgError: Singular matrix

In [14]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print("="*30)
print(A.transpose())
print("="*30)
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
