In [2]:
import numpy as np
import torch
from tensorboardX import SummaryWriter

writer = SummaryWriter(logdir='data\\now2')  
print(writer.logdir)  
writer.add_scalar("scalar", 3)  
writer.close()  

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data, x_data.dtype)

tensor([[1, 2],
        [3, 4]]) torch.int64


In [4]:
np_data = np.array(data)
x_np = torch.from_numpy(np_data)
print(np_data, np_data.dtype)

[[1 2]
 [3 4]] int32


In [8]:
ones = torch.ones_like(x_data)
rand = torch.rand_like(x_data, dtype=torch.float64)
print(ones)
print(rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.3990, 0.2711],
        [0.6492, 0.9037]], dtype=torch.float64)


In [11]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.0777, 0.1819, 0.0213],
        [0.7038, 0.2594, 0.9913]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
print(x_data.shape)
print(x_data.dtype)
print(x_data.device)

torch.Size([2, 2])
torch.int64
cpu


In [15]:
if torch.cuda.is_available():
    x_data = x_data.to('cuda')

In [19]:
print(x_data[0])
print(x_data[:,0])
print(x_data[:,-1])
print(x_data[...,-1])

tensor([1, 2])
tensor([1, 3])
tensor([2, 4])
tensor([2, 4])


In [27]:
print(torch.cat([x_data, x_data, x_data], dim=0))
print(torch.cat([x_data, x_data, x_data], dim=1))

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])
tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])


In [51]:
mdata = torch.ones([2,2])
y1 = mdata @ mdata.T
y2 = mdata.matmul(mdata.T)
y3 = torch.rand_like(mdata)
torch.matmul(mdata, mdata.T, out=y3)
print(y1)
print(y2)
print(y3)

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [53]:
agg = mdata.sum()
agg_item = agg.item()
print(agg_item, type(agg_item)) # 파이썬 변수로 변환

4.0 <class 'float'>


In [62]:
a = torch.tensor([[1,2],[3,4]])
print(a.t())
print(a.T)
a.t_() # 바꿔치기 연산
print(a)
a.add_(5)
성print(a)

tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([[6, 8],
        [7, 9]])


In [69]:
a = torch.tensor([[1,2],[3,4]]) # 토치 배열 생성
n = a.numpy() # 넘파이 배열 생성
print(n)
print(type(a), type(n))
a.add_(5)
print(n) # a의 값을 바꿔도 n에 반영이 된다.

[[1 2]
 [3 4]]
<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[6 7]
 [8 9]]


In [71]:
n = np.array([[1,2],[3,4]])
a = torch.from_numpy(n)
print(a)
np.add(n, 5, out=n)
print(a) # n을 바꿔도 a에 반영이 된다.

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[6, 7],
        [8, 9]], dtype=torch.int32)
