In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[12,3,4]])
print(a)
e = np.exp(a)
print(e)

[[ 1  2  3]
 [12  3  4]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [1.62754791e+05 2.00855369e+01 5.45981500e+01]]


In [6]:
def softmax_convert_into_pi_from_theta(theta):
    beta = 1.0 #역온도, inverse temperature, beta가 낮아질수록 행동이 무작위가 된다.
    m, n = theta.shape
    pi = np.zeros((m, n))
    exp_theta = np.exp(beta * theta)

    for i in range(0, m):
        pi[i, :] = exp_theta[i, :] / np.nansum(exp_theta[i, :]) # nan을 0으로 계산하여 합을 계산한다.
        print(pi)

    pi = np.nan_to_num(pi) # nan을 0으로 변환
    return pi

In [7]:
softmax_convert_into_pi_from_theta(a)

[ 2.71828183  7.3890561  20.08553692]
30.19287485057736
[1.62754791e+05 2.00855369e+01 5.45981500e+01]
162829.47510596027


array([[9.00305732e-02, 2.44728471e-01, 6.65240956e-01],
       [9.99541338e-01, 1.23353201e-04, 3.35308764e-04]])