In [1]:
import numpy as np

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
A.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [5]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[4, 3],[2, 1]])
C = np.array([[0, 1],[1, 0]])

In [7]:
A+B

array([[5, 5],
       [5, 5]])

In [9]:
3*C

array([[0, 3],
       [3, 0]])

In [11]:
A + 2*C

array([[1, 4],
       [5, 4]])

In [15]:
O = np.zeros((2,2), dtype=np.int32)
O

array([[0, 0],
       [0, 0]], dtype=int32)

In [17]:
A*B # 원소끼리 곱함

array([[4, 6],
       [6, 4]])

In [42]:
A@B # dot product

array([[ 8,  5],
       [20, 13]])

In [43]:
np.dot(A,B)

array([[ 8,  5],
       [20, 13]])

In [33]:
M = np.zeros((2,2), dtype=np.int32)
for i in range(2):
    for j in range(2):
        for k in range(2):
            M[i, j] += A[i, k] * B[k, j]
M # dot product 직접 구현

array([[ 8,  5],
       [20, 13]], dtype=int32)

In [38]:
A/B # 각 원소끼리 나눔

array([[0.25      , 0.66666667],
       [1.5       , 4.        ]])

In [36]:
A%B # 각 원소끼리 나눈 나머지

array([[1, 2],
       [1, 0]])

In [41]:
A//B #각 원소끼리 나눈 몫

array([[0, 0],
       [1, 4]])

In [47]:
I2 = np.identity(2) #항등행렬 생성
I2

array([[1., 0.],
       [0., 1.]])

In [49]:
np.eye(2) # 항등행렬 생성

array([[1., 0.],
       [0., 1.]])

In [51]:
np.eye(3,2) # eye 함수는 mxn 행렬을 만들 수 있다.

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [53]:
np.eye(3, k=1) # 삼각행렬을 만들 수 있다.

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [61]:
np.dot(A, I2) == A

array([[ True,  True],
       [ True,  True]])

In [64]:
np.all(np.dot(A, I2) == A)

True

In [67]:
np.linalg.det(A) # determinant

-2.0000000000000004

In [70]:
np.linalg.inv(A) # 가우스-조단 소거법을 이용한 역행렬

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [74]:
A = np.array([[1,2,3], [4,5,6]])
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])