In [ ]:
# 시험공부 모델과 연습문제의 상태가치 함수 계산

In [1]:
import numpy as np

In [2]:
PP = np.array([ 
    [0., 0.4, 0., 0.3, 0.3, 0.],
    [0., 0., 0.4, 0.5, 0.1, 0.],
    [0., 0., 0., 0.5, 0., 0.5],
    [0., 0., 0., 0.8, 0., 0.2],
    [0., 0.1, 0., 0.5, 0.2, 0.2],
    [0.,0., 0., 0., 0., 1.0]
    ])

In [3]:
print(PP.shape)
print("="*20)
for j in range(PP.shape[0]):
    print("{}-th row sum : {}".format(j+1, np.sum(PP[j])))

(6, 6)
1-th row sum : 1.0
2-th row sum : 1.0
3-th row sum : 1.0
4-th row sum : 1.0
5-th row sum : 1.0
6-th row sum : 1.0


In [4]:
# identity matrix 
Id = np.eye(6)
Id

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [5]:
# Reward matrix
RR = np.array([[-2, -2, 14, -3, -1, 0]]).T
print(RR)

[[-2]
 [-2]
 [14]
 [-3]
 [-1]
 [ 0]]


In [6]:
# gamma = 0.5 인 경우 상태가치 (state_Value) v=(I-gamma P)^(-1)R
gamma = 0.5
V = np.dot(np.linalg.inv( Id - gamma * PP), RR )
np.round(V, 3)

array([[-3.297],
       [-0.827],
       [12.75 ],
       [-5.   ],
       [-2.546],
       [ 0.   ]])

In [8]:
# gamma = 1. 인 경우 상태가치 (state_Value)
gamma = 1.
V = np.dot(np.linalg.inv( Id - gamma * PP), RR )
np.round(V, 3)

LinAlgError: Singular matrix

In [9]:
# 연습문제의 경우 : 전이확률 행렬 부터 구해보자.
PP2 =np.array([
    [0., 0.5, 0., 0., 0., 0., 0., 0., 0.5],
    [0.5, 0., 0.5, 0., 0., 0., 0., 0., 0.],
    [0., 0.5, 0., 0.5, 0., 0., 0., 0., 0.],
    [0., 0., 0.5, 0., 0.5, 0., 0., 0., 0.],
    [0., 0., 0., 0.5, 0., 0.5, 0., 0., 0.],
    [0., 0., 0., 0., 0.5, 0., 0.5, 0., 0.],
    [0., 0., 0., 0., 0., 0.5, 0., 0.5, 0.],
    [0., 0., 0., 0., 0., 0., 0.5, 0., 0.5],
    [0.5, 0., 0., 0., 0., 0., 0., 0.5, 0.]
])

In [10]:
print(PP2.shape)
for j in range(PP2.shape[0]):
    print("{}-th row sum {}".format(j+1, np.sum(PP2[j])))

(9, 9)
1-th row sum 1.0
2-th row sum 1.0
3-th row sum 1.0
4-th row sum 1.0
5-th row sum 1.0
6-th row sum 1.0
7-th row sum 1.0
8-th row sum 1.0
9-th row sum 1.0


In [11]:
# little more clever way??
PP3 = np.zeros((9,9))
PP3.shape

(9, 9)

In [12]:
for j in range(9):
    PP3[j, (j-1)%9] = 0.5
    PP3[j, (j+1)%9] =0.5

In [13]:
np.sum((PP2-PP3)**2)

0.0

In [14]:
# Reward matrix
RR2 = np.array([[-10, 1, 1, 1, 0, -1, -1, -1, 10]]).T
print(RR2)

[[-10]
 [  1]
 [  1]
 [  1]
 [  0]
 [ -1]
 [ -1]
 [ -1]
 [ 10]]


In [15]:
# gamma = 0.5 인 경우 상태가치 (state_Value) , 전치행렬로 꼭 쓸 필요는 없다. 
gamma = 0.5
Id2 = np.eye(9)
V2 = np.dot(np.linalg.inv( Id2 - gamma * PP3), RR2 )
np.round(V2, 3)

array([[-8.151],
       [-0.755],
       [ 1.132],
       [ 1.283],
       [-0.   ],
       [-1.283],
       [-1.132],
       [ 0.755],
       [ 8.151]])