pip install seeborn  
pip install pandas-datareader

In [1]:
import gym
e = gym.make('CartPole-v0')
obs = e.reset()
obs

array([-0.0228143 , -0.00069692, -0.00676679, -0.02860041])

In [2]:
import torch
import numpy as np
print(torch.__version__)

1.8.0


## 파이토치 텐서를 만드는 법

In [3]:
a = torch.FloatTensor(3,2)
b = torch.LongTensor(3,2)
c = torch.ByteTensor(3,2)
print(a)
print(b)
print(c)

tensor([[-6.5109e+33,  4.5862e-41],
        [-6.3460e+33,  4.5862e-41],
        [-6.3460e+33,  4.5862e-41]])
tensor([[140569858608448, 140569858608448],
        [140569325402864, 140569325402928],
        [140569325402992, 140569325407648]])
tensor([[161,   0],
        [131,   1],
        [100,   2]], dtype=torch.uint8)


## 리스트로 텐서 만드는 법

In [4]:
print(torch.tensor([1,2,3]))
print(torch.tensor([1.0, 2, 3]))
print(torch.FloatTensor([[1,2,3],[1,2,3]]))

tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [1., 2., 3.]])


## 모든 원소를 0으로 만드는 법

In [5]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 넘파이에 매개변수 넣어서 타입변경

In [6]:
n = np.zeros(shape=(3,2), dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 텐서에 매개변수 넣어서 타입 변경

In [7]:
n = np.zeros(shape=(3,2))
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 스칼라 텐서 만들고 접근하기(item)

In [8]:
a = torch.tensor([1,2,3])
print(a)
s = a.sum()
print(s.item())

print(torch.tensor([1]))

tensor([1, 2, 3])
6
tensor([1])


## GPU 사용하기
### wsl2는 사용불가

a = torch.FloatTensor([2,3])  
ca = a.cuda()  
a + 1  
ca + 1  
ca.device  

## Gradient

In [13]:
v1 = torch.tensor([1.0, 1.0], requires_grad=True)
v2 = torch.tensor([2.0, 2.0])
v_sum = v1 + v2
v_res = (v_sum * 2).sum()
v_res

tensor(12., grad_fn=<SumBackward0>)

In [17]:
print(v1.is_leaf, v2.is_leaf)
print(v_sum.is_leaf, v_res.is_leaf)
print(v1.requires_grad)
print(v2.requires_grad)
print(v_sum.requires_grad)
print(v_res.requires_grad)

True True
False False
True
False
True
True
