In [87]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, optimizers
import numpy as np

In [77]:
input_layer = layers.Input(shape=(2))
hidden = layers.Dense(3, name='hidden')(input_layer)
output1 = layers.Dense(1, name='output1')(hidden)
output2 = layers.Dense(1, name='output2')(hidden)

nn = keras.Model(inputs=[input_layer], outputs=[output1, output2], name='nn')
print(nn.summary())

Model: "nn"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_9 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
hidden (Dense)                  (None, 3)            9           input_9[0][0]                    
__________________________________________________________________________________________________
output1 (Dense)                 (None, 1)            4           hidden[0][0]                     
__________________________________________________________________________________________________
output2 (Dense)                 (None, 1)            4           hidden[0][0]                     
Total params: 17
Trainable params: 17
Non-trainable params: 0
___________________________________

In [78]:
weights = nn.get_weights()
for w in weights:
        print(w)

[[ 0.61822844  0.7170044  -0.90203345]
 [ 0.01246011 -0.003178    0.3943212 ]]
[0. 0. 0.]
[[ 1.0900728 ]
 [-0.05918622]
 [-0.89401567]]
[0.]
[[-0.6671704 ]
 [-0.43414205]
 [ 0.8918451 ]]
[0.]


In [79]:
inputs = tf.convert_to_tensor([[2,2]])
a,b = nn(inputs)
a,b = a.numpy(), b.numpy()
a,b

(array([[2.1983008]], dtype=float32), array([[-2.366959]], dtype=float32))

In [80]:
nn.layers[1].get_weights()[0][0]

array([ 0.61822844,  0.7170044 , -0.90203345], dtype=float32)

In [81]:
nn.trainable_variables

[<tf.Variable 'hidden/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 0.61822844,  0.7170044 , -0.90203345],
        [ 0.01246011, -0.003178  ,  0.3943212 ]], dtype=float32)>,
 <tf.Variable 'hidden/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'output1/kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[ 1.0900728 ],
        [-0.05918622],
        [-0.89401567]], dtype=float32)>,
 <tf.Variable 'output1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'output2/kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[-0.6671704 ],
        [-0.43414205],
        [ 0.8918451 ]], dtype=float32)>,
 <tf.Variable 'output2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [93]:
optimizer = optimizers.Adam(learning_rate=1e-3, epsilon=1e-3)
with tf.GradientTape() as tape:
    loss = tf.convert_to_tensor(1,dtype=float)
grads = tape.gradient(loss, nn.trainable_variables)
optimizer.apply_gradients(zip(grads, nn.trainable_variables))

tf.Tensor(1.0, shape=(), dtype=float32)


ValueError: No gradients provided for any variable: ['hidden/kernel:0', 'hidden/bias:0', 'output1/kernel:0', 'output1/bias:0', 'output2/kernel:0', 'output2/bias:0'].

In [4]:
import inspect
inspect.getfile(inspect.currentframe())

'<ipython-input-4-5c735c84e9ea>'